version: 0.0
os: linux

permissions:
  - object: /home/ubuntu/csye6225/webapp/
    owner: ubuntu
    group: ubuntu
files:             
  - source: ./
    destination: /home/ubuntu/csye6225/webapp/

  
hooks:
  ApplicationStop:
   - location: ./codedeploy/applicationStop.sh
     timeout: 180
     runas: ubuntu
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 300
      runas: ubuntu    
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 100
      runas: ubuntu